---
spring:
  profiles: default
#server:
  #port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified. 
words: NoProfileSelected
---
spring:
  profiles: sentence
words: NotApplicable
    
---
spring:
  profiles: subject
words: I,You,He,She,It
  
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
#words: reasonable,leaky,suspicious,ordinary,unlikely
words: unas,palabras,en,espaniol

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
